[project]
name = "fetchcraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fetchcraft-core",
    "fetchcraft-openai-server",
    "fetchcraft-openapi-server",
    "fetchcraft-mcp-server",
    "fetchcraft-parsing-docling",
]

[tool.uv]

[tool.uv.workspace]
members = [
    "packages/fetchcraft-core",
    "packages/fetchcraft-parsing-docling",
    "fetchcraft-demos/fetchcraft-openapi-server",
    "fetchcraft-demos/fetchcraft-openai-server",
    "fetchcraft-demos/fetchcraft-mcp-server",
]

[tool.uv.sources]
fetchcraft-core = { workspace = true }
fetchcraft-parsing-docling = { workspace = true }
fetchcraft-openapi-server = { workspace = true }
fetchcraft-openai-server = { workspace = true }
fetchcraft-mcp-server = { workspace = true }

